**Library Imports**

In [18]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

In [19]:
import os
import sys
print(sys.version)   # Python version information

3.4.4 |Anaconda 2.4.0 (64-bit)| (default, Jan 11 2016, 13:54:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]


In [20]:
from sympy import *  # Symbolic mathematics
import sympy

In [21]:
import numpy as np   # N-Dimensional arrays and numerical routines
import pandas as pd  # Data structures and data analysis tools
import scipy         # Numerical routines

In [22]:
#import numba        # Decorators for speeding up python functions

In [23]:
#from astropy import constants  # Physical Constants
#from astropy import units      # Physical Units

In [24]:
import matplotlib as mpl  # Standard plotting library
import matplotlib.pyplot as plt 
import seaborn as sns     # Statistical plotting and improved plot style
#import bokeh             # Interactive visualization library

In [25]:
from sympy.utilities.autowrap import ufuncify  # Creates numerical methods 
                                               # from symbolic expressions

In [26]:
from sympy import abc       # Symbolic variables
from sympy import pi as Pi  # Symbolic pi
from sympy import I as I    # Symbolic imaginary unit

**Display**

In [27]:
from IPython.display import display

In [28]:
from IPython.display import set_matplotlib_formats  
set_matplotlib_formats('pdf', 'png')

In [29]:
import ipywidgets

**Settings & Options**

In [30]:
np.set_printoptions(precision=5, threshold=100, edgeitems=3, linewidth=75, 
                    suppress=False, nanstr=None, infstr=None, 
                    formatter=None)

In [31]:
pandas_options = {'display.chop_threshold': None,
                  'display.precision': 4,
                  'display.max_columns': 8,
                  'display.max_rows': 8,
                  'display.max_info_columns': 8,
                  'display.max_info_rows': 8}
for key, val in pandas_options.items():
    pd.set_option(key, val)

In [32]:
sympy.interactive.printing.init_printing(use_latex='mathjax')

In [33]:
# os.system('ipython nbconvert --to pdf {filename}.ipynb')

**Custom functions**

In [34]:
latex_path = os.path.join(os.getcwd(), 'latex', 'figures')
def figure_path(fname): 
    return os.path.join(latex_path, fname)
print(os.getcwd())

/home/jaan/Dropbox/Projects/Crowd-Dynamics/documentation/notebooks


**Resources**

- [Simulating dynamical features of escape panic](http://www.nature.com/nature/journal/v407/n6803/full/407487a0.html)

- [Patient and impatient pedestrians in a spatial game for egress congestion](http://journals.aps.org/pre/abstract/10.1103/PhysRevE.87.012802)

- [Power Law](http://motion.cs.umn.edu/PowerLaw/)

- [Universal Power Law Governing Pedestrian Interactions](http://journals.aps.org/prl/abstract/10.1103/PhysRevLett.113.238701)


# DOC

In [ ]:
%matplotlib inline

$R =\begin{bmatrix}\cos \theta & -\sin \theta \\  \sin \theta & \cos \theta \\\end{bmatrix}$

In [ ]:
theta = symbols('theta', real=True)
rot = Matrix([[cos(theta), -sin(theta)],
              [sin(theta), cos(theta)]])

In [ ]:
rot

In [ ]:
rot90 = rot.subs(theta, Pi/2)

In [ ]:
rot90

In [ ]:
arg = symbols('t_0:2')

In [ ]:
t = Matrix(arg)

In [ ]:
A = Matrix.hstack(rot90 * t, -t)

In [ ]:
A_inv = simplify(A **-1)

In [ ]:
A_inv = A_inv.replace(t[0]**2 + t[1]**2, 1)

In [ ]:
A_inv

In [ ]:
q = symbols('q_0:2_0:2')
q

In [ ]:
q = symbols('x_0:2 y_0:2')
q

In [ ]:
Q = Matrix([q[0:2], q[2:4]])
Q

In [ ]:
A_inv * Q

In [ ]:
np.stack(([1, 2], [3, 4]))

In [ ]:
np.stack(([1, 2], [3, 4]), axis=1)

In [ ]:
list(map(int, []))

# Positions

In [ ]:
var('x_i:j dx_i:j')

In [ ]:
var('x_ij dx_ij')

In [ ]:
((x_i + dx_i) - (x_j + dx_j))**2

In [ ]:
(dx_ij + x_ij)**2

In [ ]:
_.expand()

# Numba

In [63]:
import numba
import numpy as np


@numba.jit( nopython=True, nogil=True)
def f_random_fluctuation(size, f_max=1):
    """

    :param size:
    :param f_max: Maximum magnitude of the force
    :return:
    :return: Uniformly distributed random force.
    """
    force = np.zeros((size, 2))
    for i in range(size):
        angle = np.random.uniform(0, 2 * np.pi)
        magnitude = np.random.uniform(0, f_max)
        force[i][0] = magnitude * np.cos(angle)
        force[i][1] = magnitude * np.sin(angle)
    return force

In [68]:
print(f_random_fluctuation(100))

[[ 0.27629  0.34003]
 [-0.23808  0.80466]
 [ 0.13863  0.13121]
 ..., 
 [ 0.06915 -0.15615]
 [ 0.28774 -0.18159]
 [ 0.08969 -0.03324]]


In [66]:
%timeit f_random_fluctuation(100)

10000 loops, best of 3: 106 µs per loop


In [72]:
np.ones((4, 2)) / np.arange(4).reshape((4, 1))

array([[     inf,      inf],
       [ 1.     ,  1.     ],
       [ 0.5    ,  0.5    ],
       [ 0.33333,  0.33333]])

In [78]:
arr  = np.arange(10).reshape((10, 1))

In [79]:
arr

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [82]:
arr[0, 0]

0