**Library Imports**

In [2]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

In [3]:
import os
import sys
print(sys.version)   # Python version information

3.4.4 |Anaconda 2.4.0 (64-bit)| (default, Jan 11 2016, 13:54:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]


In [4]:
from sympy import *  # Symbolic mathematics
import sympy

In [5]:
import numba        # Decorators for speeding up python functions

In [6]:
#from astropy import constants  # Physical Constants
#from astropy import units      # Physical Units

In [7]:
import matplotlib as mpl  # Standard plotting library
import matplotlib.pyplot as plt 
import seaborn as sns     # Statistical plotting and improved plot style
#import bokeh             # Interactive visualization library

In [8]:
from sympy.utilities.autowrap import ufuncify  # Creates numerical methods 
                                               # from symbolic expressions

In [9]:
from sympy import abc       # Symbolic variables
from sympy import pi as Pi  # Symbolic pi
from sympy import I as I    # Symbolic imaginary unit

**Display**

In [10]:
from IPython.display import display

In [11]:
from IPython.display import set_matplotlib_formats  
set_matplotlib_formats('pdf', 'png')

In [12]:
import ipywidgets

**Settings & Options**

In [13]:
import numpy as np   # N-Dimensional arrays and numerical routines
import scipy         # Numerical routines

np.set_printoptions(precision=5, threshold=100, edgeitems=3, linewidth=75, 
                    suppress=False, nanstr=None, infstr=None, 
                    formatter=None)

In [14]:
import pandas as pd  # Data structures and data analysis tools

pandas_options = {'display.chop_threshold': None,
                  'display.precision': 4,
                  'display.max_columns': 8,
                  'display.max_rows': 8,
                  'display.max_info_columns': 8,
                  'display.max_info_rows': 8}
for key, val in pandas_options.items():
    pd.set_option(key, val)

In [15]:
sympy.interactive.printing.init_printing(use_latex='mathjax')

# Velocity Relative Position to Linear Wall

Agent position $ \mathbf{x} $ velocity $ \mathbf{v} $ and linear wall params $ \mathbf{p}_0 $ and $ \mathbf{p}_1 $

$ \mathbf{q}_0 = \mathbf{p}_0 - \mathbf{x} $

$ \mathbf{q}_1 = \mathbf{p}_1 - \mathbf{x} $

$ \pm \hat{\mathbf{n}} $

$ \mathbf{x} + a \mathbf{v} = \mathbf{p}_0 + b (\mathbf{p}_1 - \mathbf{p}_0), \quad a \in \mathbb{R}^{+},\quad b \in [0, 1] $

$ [\mathbf{v}, -\mathbf{p}] \cdot [a,  b] = \mathbf{q}_0, \quad  \mathbf{p} = \mathbf{p}_1 - \mathbf{p}_0 $

In [16]:
from bokeh.plotting import show, Figure,output_notebook

In [17]:
output_notebook()

Loading BokehJS ...

In [31]:
v = np.random.uniform(-1, 1, 2)

In [32]:
np.arctan2(v[0], v[1])

-0.56721383229

In [33]:
x = np.random.uniform(-1, 1, (3, 2))

In [36]:
np.arctan2(x[:, 0], x[:, 1])

array([ 0.33481, -2.75154,  1.89632])

In [46]:
(-np.pi) % (2 * np.pi)

3.141592653589793

In [49]:
np.arange(-2 * pi, 2 * pi, pi / 2)

array([-2*pi, -3*pi/2, -pi, -pi/2, 0, pi/2, pi, 3*pi/2], dtype=object)

In [50]:
_ % (2*pi)

array([0, pi/2, pi, 3*pi/2, 0, pi/2, pi, 3*pi/2], dtype=object)

In [52]:
np.random.uniform(-1, 1, 100)

array([ 0.0186 ,  0.6039 , -0.86001, -0.70751,  0.68088,  0.1148 ,
        0.35957,  0.54533, -0.24757,  0.03704, -0.70142,  0.99908,
        0.46049, -0.91464,  0.12858,  0.7978 ,  0.18684,  0.52801,
        0.04605,  0.74093, -0.43229,  0.32394,  0.87891, -0.23872,
       -0.14003, -0.37329, -0.43863, -0.25502, -0.94905, -0.3916 ,
        0.78196, -0.05199, -0.97577, -0.5485 ,  0.92807, -0.75172,
        0.1246 ,  0.42645,  0.93401,  0.34573, -0.57848,  0.4476 ,
       -0.2661 ,  0.04859, -0.62832, -0.11047, -0.01183,  0.88607,
        0.43532,  0.33663, -0.37086, -0.35779,  0.09022, -0.01796,
        0.14972,  0.13609,  0.84375,  0.32419,  0.42032,  0.93766,
       -0.26662, -0.03158,  0.07479,  0.92719,  0.80572, -0.15719,
       -0.9611 , -0.72927, -0.36145,  0.2143 ,  0.71339,  0.78944,
       -0.34237, -0.95554,  0.29339, -0.63134,  0.85299, -0.47335,
        0.44222, -0.43939,  0.73461, -0.82773, -0.94903,  0.7441 ,
        0.03407, -0.22915,  0.40816,  0.26712, -0.18938,  0.83

In [53]:
np.argmin(_)

32

In [61]:
np.linalg.inv((np.array((1, 2)), np.array((3, 4))))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [63]:
np.linalg.inv(np.array(((1, 2), (3, 4))))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [67]:
np.arctan2(0, 0)

0.0