**Library Imports**

In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

In [2]:
import os
import sys
print(sys.version)   # Python version information

3.4.4 |Anaconda 2.4.0 (64-bit)| (default, Jan 11 2016, 13:54:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]


In [3]:
from sympy import *  # Symbolic mathematics
import sympy

In [4]:
import numba        # Decorators for speeding up python functions

In [5]:
#from astropy import constants  # Physical Constants
#from astropy import units      # Physical Units

In [6]:
import matplotlib as mpl  # Standard plotting library
import matplotlib.pyplot as plt 
import seaborn as sns     # Statistical plotting and improved plot style
#import bokeh             # Interactive visualization library

In [7]:
from sympy.utilities.autowrap import ufuncify  # Creates numerical methods 
                                               # from symbolic expressions

In [8]:
from sympy import abc       # Symbolic variables
from sympy import pi as Pi  # Symbolic pi
from sympy import I as I    # Symbolic imaginary unit

**Display**

In [9]:
from IPython.display import display

In [10]:
from IPython.display import set_matplotlib_formats  
set_matplotlib_formats('pdf', 'png')

In [11]:
import ipywidgets

**Settings & Options**

In [12]:
import numpy as np   # N-Dimensional arrays and numerical routines
import scipy         # Numerical routines

np.set_printoptions(precision=5, threshold=100, edgeitems=3, linewidth=75, 
                    suppress=False, nanstr=None, infstr=None, 
                    formatter=None)

In [13]:
import pandas as pd  # Data structures and data analysis tools

pandas_options = {'display.chop_threshold': None,
                  'display.precision': 4,
                  'display.max_columns': 8,
                  'display.max_rows': 8,
                  'display.max_info_columns': 8,
                  'display.max_info_rows': 8}
for key, val in pandas_options.items():
    pd.set_option(key, val)

In [14]:
sympy.interactive.printing.init_printing(use_latex='mathjax')

# Velocity Relative Position to Linear Wall

Agent position $ \mathbf{x} $ velocity $ \mathbf{v} $ and linear wall params $ \mathbf{p}_0 $ and $ \mathbf{p}_1 $

$ \mathbf{q}_0 = \mathbf{p}_0 - \mathbf{x} $

$ \mathbf{q}_1 = \mathbf{p}_1 - \mathbf{x} $

$ \pm \hat{\mathbf{n}} $

$ \mathbf{x} + a \mathbf{v} = \mathbf{p}_0 + b (\mathbf{p}_1 - \mathbf{p}_0), \quad a \in \mathbb{R}^{+},\quad b \in [0, 1] $

$ [\mathbf{v}, -\mathbf{p}] \cdot [a,  b] = \mathbf{q}_0, \quad  \mathbf{p} = \mathbf{p}_1 - \mathbf{p}_0 $

In [22]:
np.random.uniform(size=(10, 2, 2))

array([[[  9.39976e-04,   6.56330e-01],
        [  3.39824e-01,   6.57788e-01]],

       [[  7.47491e-01,   4.42665e-01],
        [  1.67629e-01,   2.21832e-01]],

       [[  7.71742e-01,   6.81323e-01],
        [  9.70875e-01,   6.48199e-01]],

       [[  4.18087e-01,   1.09445e-01],
        [  1.94982e-01,   7.91621e-02]],

       [[  4.86622e-01,   9.45794e-01],
        [  1.51430e-02,   2.28730e-01]],

       [[  3.43993e-01,   5.02118e-01],
        [  2.78816e-01,   1.08873e-01]],

       [[  3.96318e-01,   7.46787e-01],
        [  6.32555e-01,   1.47627e-01]],

       [[  4.27333e-01,   4.93787e-01],
        [  7.26945e-02,   5.59930e-02]],

       [[  4.15764e-01,   6.24030e-01],
        [  6.54938e-01,   4.83738e-01]],

       [[  9.24595e-02,   4.18168e-01],
        [  7.13335e-01,   8.34022e-01]]])

In [23]:
_[:, :, 0].flatten()

array([  9.39976e-04,   3.39824e-01,   7.47491e-01,   1.67629e-01,
         7.71742e-01,   9.70875e-01,   4.18087e-01,   1.94982e-01,
         4.86622e-01,   1.51430e-02,   3.43993e-01,   2.78816e-01,
         3.96318e-01,   6.32555e-01,   4.27333e-01,   7.26945e-02,
         4.15764e-01,   6.54938e-01,   9.24595e-02,   7.13335e-01])

In [24]:
z = np.zeros(10)

In [25]:
z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [26]:
z[::2] = np.ones(5)

In [27]:
z

array([ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.])