In [1]:
import os

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
from tabulate import tabulate

In [5]:
from sympy import *

In [6]:
from sympy import init_printing

In [7]:
init_printing(use_latex="mathjax")

In [8]:
from bokeh.plotting import output_notebook, figure, show

In [9]:
output_notebook()

Loading BokehJS ...

In [10]:
import matplotlib.pyplot as plt

In [11]:
import seaborn

In [12]:
from scipy.stats import truncnorm as tn

In [13]:
%matplotlib inline

In [15]:
import numba

In [17]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [18]:
_.dot(np.array([1, 2]))

array([ 5, 11])

In [19]:
np.array((np.nan, 1
        ))

array([ nan,   1.])

In [20]:
np.argmin(_)

0

In [23]:
np.nanargmin(_19)

1